### ISSUE TITLE
Display version number

### ISSUE THREAD

**Issue by jimt** [huideyeren/anshitsu#31]
I suggest adding a `--version` option _OR_ show the **anshitsu** version number in the help text.

**Comment by huideyeren** [comment]
Thank you for your suggestion.
I definitely need to do this.
Thank you in advance for your time.

**Comment by huideyeren** [comment]
This article (in Japanese) may be helpful for the version.
https://qiita.com/ieiringoo/items/4bef4fc9975803b08671

**Comment by huideyeren** [comment]
fixed by #40
